spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database: postgresql
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: Initial migration
    baseline-version: 1.0

