spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: eureka-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
