spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: customer-service
  profiles:
    active: docker

server:
  port: 8090

# Basic Eureka config as fallback
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/