spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

  # 🔥 Disable Spring Boot OTLP log export
  otlp:
    logging:
      enabled: false

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  service:
    name: ${spring.application.name}

  # 🔥 Disable OTEL logs (logs → Loki only)
  logs:
    exporter: none

  # 🔥 Disable OTEL metrics (metric
