spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: product
  profiles:
    active: docker

server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/