spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
        name: productservice
server:
  port: 8091
info:
   app.name: product-service
   build.version: ${git.commit.id.abbrev}
   contact.email: e-commerce@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: "*"